name: Yarn CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    strategy:
      matrix:
        node_version: [16, 18]
        node_arch: [x86, x64]
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node_version }}
        architecture: ${{ matrix.node_arch }}
    - run: npm install yarn@latest
    - run: node .yarn/releases/yarn-3.2.2.cjs
