name: Yarn CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    strategy:
      matrix:
        node_version: [16, 18]
        node_arch: [x86, x64]
        yarn_version: [3.3.0, 3.2.4, 3.1.1, 3.0.0]
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node_version }}
        architecture: ${{ matrix.node_arch }}
    - run: corepack enable
    - run: corepack prepare yarn@${{ matrix.yarn_version }} --activate
    - run: yarn
