name: Yarn CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, windows-2022]
        node_version: [18, 19]
        node_arch: [x86, x64]
        yarn_version: [3.3.0, 3.2.4]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node_version }}
        architecture: ${{ matrix.node_arch }}
    - run: corepack enable
    - run: corepack prepare yarn@${{ matrix.yarn_version }} --activate
    - run: yarn set version ${{ matrix.yarn_version }}
    - run: yarn config set enableImmutableInstalls false
    - run: yarn
